org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.23
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=citylife
mod_name=City Life
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.lscity.citylife
mod_authors=soloassist5-cmd
mod_description=Smartphones with apps and smart locks for a modern city roleplay pack.
